ignore:
  - "tests"                              # Don't need to inventory unit tests, they are covered by design
  - "setup.py"                           # Run only when installing TopCoffea
coverage:
  status:
    project:
      default:
        threshold: 90%
    patch:
      default:
        threshold: 90%
